# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js:
  - 10.8.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
before_script:
  - git config user.name "rosuH"
  - git config user.email "rosuh@qq.com"
  - sed -i'' "s~https://github.com/rosuH/Blog.git~https://${GITHUB_ACCESS_TOKEN}@github.com/rosuH/Blog.git~" _config.yml
  - cat _config.yml

script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - hexo deploy
# End: Build LifeCycle

