# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js:
  - 10.8.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli
  - npm install -g firebase-tools

# Start: Build Lifecycle
install:
  - npm install

script:
  - hexo clean
  - hexo generate
  - firebase deploy --non-interactive --project ${FIREBASE_PROJECT}  --token ${FIREBASE_TOKEN}
