favicon: /favicon.ico

post:
  append:
    __: post.append

menu:
  - url: /archives
    icon: czs-folder-l
    title: 归档
  - url: /categories
    icon: czs-bookmark-l
    title: 分类
  - url: /tags
    icon: czs-tag-l
    title: 标签
  - placeholder: true
  - url: https://rosuh.me
    icon: czs-user-l
    title: 关于我

sidebar:
  title: false
  subtitle: true
  description: false
  avatar: /assets/about/avatar.png
  welcome: ">  现实就是答案。"
  social:
    - url: https://t.me/rosuh
      icon: czs-telegram
      title: Telegram
    - url: https://wiki.rosuh.me
      icon: czs-book
      title: Wiki
    - url: https://github.com/rosuH
      icon: czs-github
      title: GitHub
    - url: https://www.v2ex.com/member/rosu
      icon: czs-v2ex
      title: V2EX
    - url: https://twitter.com/rosu_h
      icon: czs-twitter
      title: Twitter
    - url: mailto:pokk366@gmail.com
      icon: czs-message-l
      title: Gmail
    - url: /atom.xml
      icon: czs-rss
      title: RSS 订阅
  links:
    "rosu's WIKI": http://wiki.rosuh.me/
    "Avatar: Created by IcontFont-ColinXu": http://iconfont.cn/user/detail?spm=a313x.7781069.1998910419.dfa9d9a29&uid=496384

    More: /links

disqus_shortname: blog-nhbebwyjaw

# Google Analytics
google_analytics: UA-82992902-3 

since: 2017
