name: Gatsby Publish

on:
  push:
    branches:
      - feat_migrate_to_gatsby

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_KEY }}
          deploy-branch: master
